### ISSUE TITLE
TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by LastRoze** [appu1232/Discord-Selfbot#341] opened 2018-06-30 11:55 UTC
Help, just got this Error today.

- Python 3.5.3
- Pip 9.0.1

![capture](https://user-images.githubusercontent.com/9519234/42124954-800f40de-7c9f-11e8-9594-169e7f08012c.PNG)

**Comment by xyn-n** [comment] 2018-06-30 19:06
I have this issue, too.

**Comment by nanopulga** [comment] 2018-06-30 21:46
Same here...

**Comment by ggrey22** [comment] 2018-06-30 23:06
I'm also having this issue

**Comment by professorshinonome** [comment] 2018-07-01 03:51
Also experiencing this. Quite a few of the bot's commands error, not sure if that's tied to this at all or not.

**Comment by Blitzsy** [comment] 2018-07-01 04:34
Discord.py rewrite committed a change which broke something in the selfbot. You will need to wait until a fix is made on the selfbot side. I managed to find a temporary workaround by changing the pip requirements.txt.

Find `
git+https://github.com/Rapptz/discord.py@rewrite` 
and replace it with `git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233`

**Comment by LastRoze** [comment] 2018-07-01 07:05
@Blitzsy Thanks for the workaround man, really appreciated it.

**Comment by LyricLy** [comment] 2018-07-01 07:59
The issue is likely to be fixed soon on discord.py's side. It seems as though a fix has already been PRed.

**Comment by TastyCookies124** [comment] 2018-07-01 09:01
Yay!!!! It worked Thanks Blitzsy

**Comment by MacGyverinf** [comment] 2018-07-01 17:41
this also worked for me as well
`git+https://github.com/Rapptz/discord.py@184c4302c7fe17a31893f0accf197c975200d233`

thanks

**Comment by appu1232** [comment] 2018-07-02 01:55
Just pushed the discord.py version rollback to master. Should be fixed now if you accept the update next time you run the bot.

**Closed by appu1232** 2018-07-02 01:55 UTC
