### ISSUE TITLE
Error running on VPS (Ubuntu Server 16.04)

### ISSUE THREAD

**Issue by SlimShadyIAm** [appu1232/Discord-Selfbot#248] opened 2017-11-23 09:56 UTC
> It is not advised to run the bot with root privileges.
> Continuing logging in...
> It is not advised to run the bot with root privileges.
> Continuing logging in...
> It is not advised to run the bot with root privileges.
> Continuing logging in...
> It is not advised to run the bot with root privileges.
> Continuing logging in...

This continues to loop. I made sure all the requirements are installed. I had no issues getting it to run on a home server.

**Comment by astronautlevel2** [comment] 2017-11-30 16:50
Okay, I think I see what's causing this. I'll look more into it when I get home.

**Comment by SlimShadyIAm** [comment] 2017-12-03 11:45
@astronautlevel2 you home yet? :D

**Comment by Macley-Kun** [comment] 2017-12-24 15:32
![image](https://user-images.githubusercontent.com/26381427/34327570-055d4c7a-e8c8-11e7-9cd2-d23c031a002e.png)

**Comment by shivaco** [comment] 2017-12-29 20:23
My bet is on wrong config.json setup.

**Comment by Macley-Kun** [comment] 2017-12-29 20:47
We'll see :^)

**Comment by how-do-i-code-help-me-help-hello** [comment] 2018-01-01 23:45
Having same issue on Ubuntu 17.10 x64

**Comment by how-do-i-code-help-me-help-hello** [comment] 2018-01-03 08:04
@shivaco any examples? should be easy to replicate if so

**Comment by SlimShadyIAm** [comment] 2018-01-03 08:06
Actually no, I used the same config I used on the VPS on my local server;
it worked on the local server and didn't on the VPS.

**Comment by EliteDaMyth** [comment] 2018-03-06 08:53
The issue is not with the bot its just that you are running the thing as sudo or from the root user

**Comment by shivaco** [comment] 2018-03-06 09:33
I ran it from the root user and it was working for me. 🤔

**Comment by SlimShadyIAm** [comment] 2018-03-06 09:34
Wow this issue is still going?

Same, I ran it from root on a different machine without issue.

**Comment by chenzw95** [comment] 2018-03-29 02:12
Is this still an issue?

**Comment by chenzw95** [comment] 2018-04-26 12:13
No updates, closing.

**Closed by chenzw95** 2018-04-26 12:13 UTC
Labels: bug
